version: '3.3'
services:
  backend:
    image: tictac
    environment:
      - INSTANCE_URL=http://my-environment.eba-wex99uwr.us-east-1.elasticbeanstalk.com
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      args:
          API_KEY: http://52.5.114.86:8080/tictac
    ports:
      - "5173:5173"
